version: '3.7'

services:
  psql:
    image: postgres
    container_name: 'psql'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  app:
    container_name: 'lg'
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    depends_on:
      - psql