name: Buld Docker images

on:
  push:
    branches:
      - dev

jobs:
  push-to-registry:
    name: Build and publish images to Docker Registry
    runs-on: ubuntu-latest
    needs: init
    env:
      frontend_rep: ${{ secrets.DOCKERHUB_USERNAME }}/lct-hack-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Push frontend image
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{env.frontend_rep}}:latest
          cache-from: type=registry,ref=${{env.frontend_rep}}:latest
          cache-to: type=inline
          platforms: linux/x86_64