name: Deploy application

on:
  push:
    branches:
      - dev

jobs:
  push-to-registry:
    name: Build and publish images to Docker Registry
    runs-on: ubuntu-latest
    env:
      frontend_rep: ${{ secrets.DOCKERHUB_USERNAME }}/lct-hack-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Push frontend image
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{env.frontend_rep}}:latest
          cache-from: type=registry,ref=${{env.frontend_rep}}:latest
          cache-to: type=inline
          platforms: linux/x86_64
  
  build-frontend:
    needs: push-to-registry
    name: Build and publish frontend
    runs-on: self-hosted
    steps:
      -
        name: Pull service
        run: docker compose -f docker-compose.yml pull
      -
        name: Build service
        run: docker compose -f docker-compose.yml up frontend -d --force-recreate
      -
        name: Check service
        run: docker ps -a